version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
      - 8123:8123
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      # copy server file to volume (~/storage/data/minecraft_atm7_tts/)
      GENERIC_PACK: server-1.2.3.zip
      VERSION: 1.18.2
      FORGEVERSION: 40.2.1
      MEMORY: "12G"
      ONLINE_MODE: "true"
      TZ: "Europe/Berlin"
      USE_AIKAR_FLAGS: "true"
      LOG_TIMESTAMP: "true"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ~/storage/data/minecraft_atm7_tts:/data
